### ISSUE TITLE
Issue 1 

### ISSUE THREAD

**Issue by 0367592801** [tranchiencongtd/tranchiencongtd.github.io#1]
Bài làm tốt, đúng bố cục nhưng mà tại sao lại đặt thẻ các thẻ div bên dưới trong thẻ i ? Lười ko muốn viết lại chữ nghiêng à? :V sai bản chất nhé. Sửa lại cho a nhé. A muốn hỏi 1 câu như sau: E có thấy những thuộc tính như width, height hay text-align phải viết đi viết lại giống nhau và rất nhiều lần không? Giải quyết như thế nào được nhỉ? :C giúp a nhé

**Comment by tranchiencongtd** [comment]
Anh xem lại xem thế nào nhé anh !

**Comment by 0367592801** [comment]
OK, Buổi 1 chuẩn rồi đấy
